# Generated by Django 4.0.3 on 2022-09-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='20220831_110444_wplkM8g.jpg', null=True, upload_to=''),
        ),
    ]
