# Generated by Django 4.0.3 on 2022-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='20220831_110444_wplkM8g.jpg', null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='20220831_110444_wplkM8g.jpg', null=True, upload_to='profile_image'),
        ),
    ]
